Bahamas, The: Bahamas
Bosnia and Herz.: Bosnia and Herzegovina
Cabo Verde: Cape Verde
Central African Rep.: Central African Republic
Cote d'Ivoire: Ivory Coast
Czechia: Czech Republic
Côte d'Ivoire: Ivory Coast
Gambia: The Gambia
Gambia, The: The Gambia
Holy See: Vatican City
Hong Kong SAR: Hong Kong
Iran (Islamic Republic of): Iran
Korea, Democratic People's Republic of: North Korea
Korea, South: South Korea
Macao SAR: Macau
Macao: Macau
Mainland China: China
North Macedonia: Macedonia
occupied Palestinian territory: Palestine
Republic of Ireland: Ireland
Republic of Korea: South Korea
Republic of Moldova: Moldova
Republic of the Congo: Congo
Russian Federation: Russia
Saint Martin: St. Martin
Taipei and environs: Taiwan
Taiwan*: Taiwan
The Bahamas: Bahamas
Timor-Leste: East Timor
UK: United Kingdom
US: United States
Viet Nam: Vietnam
